import type { Client } from "./engine/types";

// Fifteen well-known public companies, one per industry, used as illustrative
// desks so the sort is easy to read. None is a Newsjack client; topics and
// exclusions are the demo author's guesses, not company positions.
export const CLIENTS: Client[] = [
  { id: "apple", name: "Apple", sector: "consumer tech", domain: "apple.com", blurb: "iPhone, Mac, services.", topics: ["apple", "iphone", "ipad", "mac", "ios", "app store", "smartphone", "wearable", "apple watch", "siri"], exclusions: ["child labor"] },
  { id: "jpmorgan", name: "JPMorgan Chase", sector: "banking", domain: "jpmorganchase.com", blurb: "Largest US bank.", topics: ["bank", "rates", "fed", "inflation", "mortgage", "treasury", "bond", "jpmorgan", "dimon", "lending", "recession", "boj"], exclusions: ["epstein"] },
  { id: "pfizer", name: "Pfizer", sector: "pharma", domain: "pfizer.com", blurb: "Vaccines and medicines.", topics: ["vaccine", "drug", "fda", "trial", "cancer", "pfizer", "pharma", "flu", "covid", "obesity", "glp", "measles", "tuberculosis"], exclusions: ["patient death lawsuit"] },
  { id: "tesla", name: "Tesla", sector: "autos", domain: "tesla.com", blurb: "EVs, energy storage, robotaxi.", topics: ["tesla", "ev", "electric vehicle", "musk", "self-driving", "autonomous", "robotaxi", "battery", "charging", "waymo", "humanoid", "robot"], exclusions: ["crash death"] },
  { id: "nike", name: "Nike", sector: "apparel", domain: "nike.com", blurb: "Footwear and sportswear.", topics: ["nike", "sneaker", "athlete", "nba", "nfl", "olympic", "marathon", "world cup", "sportswear", "footwear", "running"], exclusions: ["sweatshop"] },
  { id: "disney", name: "Disney", sector: "media", domain: "disney.com", blurb: "Studios, parks, streaming.", topics: ["disney", "streaming", "box office", "film", "movie", "theme park", "espn", "marvel", "star wars", "hulu", "trailer", "netflix"], exclusions: ["abuse allegation"] },
  { id: "walmart", name: "Walmart", sector: "retail", domain: "walmart.com", blurb: "Largest US retailer.", topics: ["walmart", "retail", "grocery", "shopping", "consumer spending", "tariff", "amazon", "prices", "supply chain", "made in america", "target"], exclusions: ["shooting"] },
  { id: "exxon", name: "ExxonMobil", sector: "energy", domain: "exxonmobil.com", blurb: "Oil, gas, chemicals.", topics: ["oil", "gas", "opec", "energy", "exxon", "crude", "pipeline", "lng", "refinery", "heating oil", "fuel", "emissions"], exclusions: ["oil spill"] },
  { id: "delta", name: "Delta Air Lines", sector: "airlines", domain: "delta.com", blurb: "Global airline.", topics: ["airline", "flight", "airport", "delta", "faa", "boeing", "airbus", "travel", "pilot", "airspace", "tsa"], exclusions: ["plane crash"] },
  { id: "coinbase", name: "Coinbase", sector: "crypto", domain: "coinbase.com", blurb: "Crypto exchange.", topics: ["crypto", "bitcoin", "ethereum", "stablecoin", "coinbase", "cftc", "sec", "token", "blockchain", "prediction market", "world money"], exclusions: ["hack victim"] },
  { id: "zillow", name: "Zillow", sector: "real estate", domain: "zillow.com", blurb: "Home search and data.", topics: ["housing", "home prices", "mortgage rates", "rent", "real estate", "zillow", "homebuyer", "landlord", "apartment", "housing market"], exclusions: ["eviction death"] },
  { id: "nvidia", name: "Nvidia", sector: "semiconductors", domain: "nvidia.com", blurb: "GPUs and AI infrastructure.", topics: ["nvidia", "chip", "gpu", "ai", "data center", "openai", "anthropic", "semiconductor", "dram", "memory", "model", "llm", "tsmc"], exclusions: ["export violation"] },
  { id: "starbucks", name: "Starbucks", sector: "restaurants", domain: "starbucks.com", blurb: "Coffeehouse chain.", topics: ["starbucks", "coffee", "restaurant", "fast food", "menu", "union", "barista", "minimum wage", "food prices", "diet", "nutrition"], exclusions: ["food poisoning"] },
  { id: "lockheed", name: "Lockheed Martin", sector: "defense", domain: "lockheedmartin.com", blurb: "Defense and aerospace.", topics: ["defense", "pentagon", "missile", "drone", "military", "lockheed", "f-35", "nato", "space", "nasa", "satellite", "hegseth", "ukraine"], exclusions: ["civilian casualties"] },
  { id: "unitedhealth", name: "UnitedHealth", sector: "health insurance", domain: "unitedhealthgroup.com", blurb: "Health insurer and services.", topics: ["health insurance", "medicaid", "medicare", "hospital", "unitedhealth", "insurer", "premium", "obamacare", "heart", "blood pressure", "cholesterol", "doctor"], exclusions: ["ceo shooting"] },
];
